# Generated by Django 3.2.6 on 2022-11-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tema', models.CharField(max_length=50)),
                ('users', models.ManyToManyField(related_name='_forum_forum_users_+', to='forum.Forum')),
            ],
        ),
    ]
