# Generated by Django 3.2.16 on 2022-11-16 23:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20221113_2234'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='user.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forum',
            name='users',
            field=models.ManyToManyField(null=True, related_name='users', to='user.User'),
        ),
    ]
