# Generated by Django 3.2.16 on 2022-11-16 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20221113_2234'),
        ('forum', '0003_auto_20221116_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='forum',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='user.user'),
        ),
    ]
