# Generated by Django 3.2.6 on 2022-11-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_forum_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
